name: Publish

on:
  push:
    tags:
      - "*"
jobs:
  build:
    name: Publish binaries
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
      - name: Build
        run: bun run build
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          # A personal access token for the GitHub repository in which the release will be created and edited.
          # It is recommended to create the access token with the following scopes: `repo, user, admin:repo_hook`.
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/remove_redirect.user.js
          asset_name: remove_redirect.user.js
          tag: ${{ github.ref }}
          overwrite: true
